# Numpy: Package for Multidimensional Array

In [23]:
import numpy as np

In [4]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [5]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
sample_matrix=np.array(list_of_lists)

In [6]:
sample_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(5,25)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [8]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [12]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [13]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.random.rand(3,2)

array([[0.24400058, 0.64986375],
       [0.33179607, 0.24358476],
       [0.6868002 , 0.01755164]])

In [19]:
np.random.randn(3,2)

array([[-0.48592575,  0.45478591],
       [-0.52324824,  0.59557072],
       [-1.26652457,  1.19464585]])

In [20]:
np.random.randint(34,100)

50

In [21]:
np.random.randint(34,100,50)

array([44, 38, 69, 42, 45, 55, 93, 95, 91, 41, 36, 76, 74, 79, 43, 34, 79,
       42, 48, 42, 41, 69, 75, 70, 78, 91, 98, 67, 34, 67, 96, 86, 50, 60,
       55, 73, 45, 74, 35, 42, 39, 50, 63, 82, 47, 66, 47, 53, 59, 79])

In [26]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [27]:
sample_array.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [29]:
rand_array=np.random.randint(0,100,20)
rand_array

array([53, 19, 63, 85, 33, 28, 95, 80, 77, 35, 78, 59, 64, 82, 16, 50, 80,
       90, 22, 55])

In [30]:
rand_array.min()

16

In [31]:
rand_array.argmin()

14

In [33]:
sample_array.dtype

dtype('int32')

In [34]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
a=np.random.rand(2,3)
a

array([[0.83152801, 0.5274145 , 0.35749101],
       [0.62938614, 0.37304261, 0.3987217 ]])

In [38]:
a.T

array([[0.83152801, 0.62938614],
       [0.5274145 , 0.37304261],
       [0.35749101, 0.3987217 ]])

In [39]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [40]:
sample_array[3:7]

array([13, 14, 15, 16])

In [42]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [43]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [44]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [46]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [47]:
subset_sample_array[1:4]=1001
subset_sample_array

array([  10, 1001, 1001, 1001,   14,   15,   16])

In [48]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

# TWO DIMENSIONAL ARRAY


In [49]:
import numpy as np

In [50]:
sample_matrix=np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [51]:
sample_matrix[2][3]

7

In [52]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [53]:
sample_matrix[2]

array([56, 76, 24,  7])

In [54]:
sample_matrix[:,[3,2]]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

In [55]:
sample_matrix[2]

array([56, 76, 24,  7])

In [59]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [60]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [61]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [62]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [63]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [64]:
np.max(sample_array)

19

In [65]:
np.min(sample_array)

1

In [66]:
np.std(sample_array)

5.477225575051661

In [67]:
np.mean(sample_array)

10.0

In [68]:
array=np.random.randn(3,4)
array

array([[-0.02101386,  0.64882108,  1.23802853, -0.2312446 ],
       [ 0.14441806,  0.23098914, -0.59850411, -0.96085956],
       [-0.21608684,  0.35061461,  0.43598767, -0.06364964]])

In [69]:
np.round(array,decimals=3)

array([[-0.021,  0.649,  1.238, -0.231],
       [ 0.144,  0.231, -0.599, -0.961],
       [-0.216,  0.351,  0.436, -0.064]])

In [70]:
sports=np.array(['golf','cricket','fball','cricket','fball','basketball'])
np.unique(sports)

array(['basketball', 'cricket', 'fball', 'golf'], dtype='<U10')